import { describe, expect, it } from "vitest";
import { weeklyPostText } from "./weekly-post";
import { aiAuthorshipMatch } from "./post-copy";

describe("aiAuthorshipMatch (owner 10-03 16:31: posts on the owner's accounts never say AI wrote or posted them)", () => {
  it.each([
    "This post was written by AI.",
    "Generated by ChatGPT",
    "my agent wrote this thread",
    "My agent posted this",
    "auto-posted from our pipeline",
    "posted automatically",
    "本帖由 AI 生成",
    "这条是 AI 写的",
    "这条帖子由 agent 发的",
    "内容自动生成",
    "定时发布",
  ])("blocks %s", (t) => expect(aiAuthorshipMatch(t)).not.toBeNull());

  it("lets the series theme and the product's own automation through", () => {
    expect(aiAuthorshipMatch("I let an AI agent run this project for a month. Here is what it did.")).toBeNull();
    expect(aiAuthorshipMatch(weeklyPostText([{ id: "a", name: "A", gain: 10, tagline: "" }], "10/6", "https://agentoolrank.com"))).toBeNull();
  });
});
