"use client";

import { useState } from "react";

interface StackLayer {
  name: string;
  description: string;
  tools: Array<{
    tool_id: string;
    role: string;
    note: string;
    name?: string;
  }>;
}

interface StackData {
  title: string;
  icon: string;
  difficulty?: string;
  execution_plan?: Array<{ step: string; task: string; output: string }>;
  failure_points?: string[];
  layers: StackLayer[];
}

function generateInstruction(stack: StackData): string {
  let instruction = `# ${stack.icon} ${stack.title}\n`;
  instruction += `# Generated by AgenToolRank (agentoolrank.com)\n\n`;
  instruction += `## Goal\nBuild a ${stack.title.toLowerCase()} using the following tool stack.\n\n`;

  instruction += `## Tool Stack\n`;
  for (const layer of stack.layers) {
    instruction += `### ${layer.name}\n`;
    for (const tool of layer.tools) {
      const name = tool.name || tool.tool_id;
      if (tool.role === "External") {
        instruction += `- ${name} (external service) — ${tool.note}\n`;
      } else {
        instruction += `- ${name} (${tool.role}) — ${tool.note}\n`;
        instruction += `  Docs: https://agentoolrank.com/tool/${tool.tool_id}\n`;
      }
    }
    instruction += `\n`;
  }

  if (stack.execution_plan && stack.execution_plan.length > 0) {
    instruction += `## Execution Plan\n`;
    stack.execution_plan.forEach((s) => { instruction += `${s.step}: ${s.task}\n  → Output: ${s.output}\n`; });
    instruction += `\n`;
  }

  if (stack.failure_points && stack.failure_points.length > 0) {
    instruction += `## Watch Out\n`;
    stack.failure_points.forEach((fp) => { instruction += `- ${fp}\n`; });
    instruction += `\n`;
  }

  instruction += `## Instructions\n`;
  instruction += `1. Set up the project structure following the execution plan above.\n`;
  instruction += `2. Install the Primary tools for each layer first.\n`;
  instruction += `3. Wire up integrations between layers.\n`;
  instruction += `4. Refer to each tool's docs page on AgenToolRank for setup details.\n`;

  return instruction;
}

export function InstructionBlock({ stack }: { stack: StackData }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const instruction = generateInstruction(stack);

  return (
    <div className="mt-6 border border-gray-200 rounded-xl overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-3 bg-gray-900 text-white hover:bg-gray-800 transition-colors"
      >
        <span className="flex items-center gap-2 text-sm font-medium">
          <span className="font-mono text-green-400">$</span>
          Quick Setup — paste into Claude Code / Codex / terminal
        </span>
        <div className="flex items-center gap-2">
          <span
            onClick={(e) => {
              e.stopPropagation();
              navigator.clipboard.writeText(instruction);
              setCopied(true);
              setTimeout(() => setCopied(false), 2000);
            }}
            className="text-xs px-2.5 py-1 bg-green-600 hover:bg-green-500 rounded text-white cursor-pointer transition-colors"
          >
            {copied ? "Copied! Paste into terminal" : "Copy Setup Instructions"}
          </span>
          <svg className={`w-4 h-4 transition-transform ${expanded ? "rotate-180" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>
      {expanded && (
        <pre className="p-4 bg-gray-950 text-gray-300 text-xs leading-relaxed overflow-x-auto max-h-80 overflow-y-auto font-mono">
          {instruction}
        </pre>
      )}
    </div>
  );
}
