/**
 * Soft-delist: move a tool's row from `tools` to `tools_archive` (full row + its metric_snapshots as JSON, reason, time;
 * metric_snapshots has a foreign key to tools, so those rows move with it), so it disappears
 * from every page, list and sitemap at once while staying recoverable. Discovery, expansion, review and /submit
 * all check tools_archive, so a delisted tool is not re-added automatically.
 * Usage: bun run scripts/delist-tool.ts <id> --reason="..." [--dry-run]
 *        bun run scripts/delist-tool.ts <id> --restore
 */
import { config } from "dotenv";
import { createClient } from "@libsql/client";
import { writeFileSync } from "node:fs";

config({ path: new URL("../.env.local", import.meta.url).pathname, quiet: true });
const db = createClient({ url: process.env.TURSO_DATABASE_URL!, authToken: process.env.TURSO_AUTH_TOKEN });
const id = process.argv[2];
const reason = process.argv.find((a) => a.startsWith("--reason="))?.slice(9) ?? "";
const dryRun = process.argv.includes("--dry-run");
if (!id || id.startsWith("--")) throw new Error("usage: delist-tool.ts <id> --reason=... | --restore");

const plain = (r: Record<string, unknown>) => Object.fromEntries(Object.entries(r).filter(([k]) => !/^\d+$/.test(k)));
const insert = (table: string, row: Record<string, unknown>) => {
  const cols = Object.keys(row);
  return { sql: `INSERT INTO ${table} (${cols.join(", ")}) VALUES (${cols.map(() => "?").join(", ")})`, args: Object.values(row) as never };
};

await db.execute(`CREATE TABLE IF NOT EXISTS tools_archive (
  id TEXT PRIMARY KEY, row_json TEXT NOT NULL, reason TEXT NOT NULL, archived_at TEXT NOT NULL DEFAULT (datetime('now')))`);

if (process.argv.includes("--restore")) {
  const a = (await db.execute({ sql: "SELECT row_json FROM tools_archive WHERE id = ?", args: [id] })).rows[0];
  if (!a) throw new Error(`${id} is not archived`);
  const { tool, snapshots = [] } = JSON.parse(String(a.row_json)) as { tool: Record<string, unknown>; snapshots?: Record<string, unknown>[] };
  await db.batch([
    insert("tools", tool),
    ...snapshots.map((r) => insert("metric_snapshots", r)),
    { sql: "DELETE FROM tools_archive WHERE id = ?", args: [id] },
  ], "write");
  console.log(`restored ${id}`);
} else {
  if (!reason) throw new Error("--reason is required");
  const t = (await db.execute({ sql: "SELECT * FROM tools WHERE id = ?", args: [id] })).rows[0];
  if (!t) throw new Error(`${id} not in tools`);
  const tool = plain(t);
  const snapshots = (await db.execute({ sql: "SELECT * FROM metric_snapshots WHERE tool_id = ?", args: [id] })).rows.map(plain);
  console.log(`${id}: ${String(tool.name)} — ${String(tool.tagline).slice(0, 100)}\n  snapshots: ${snapshots.length}\n  reason: ${reason}`);
  if (dryRun) process.exit(0);
  // One transaction: the archive copy exists before the rows leave `metric_snapshots` and `tools`.
  await db.batch([
    { sql: "INSERT INTO tools_archive (id, row_json, reason) VALUES (?, ?, ?)", args: [id, JSON.stringify({ tool, snapshots }), reason] },
    { sql: "DELETE FROM metric_snapshots WHERE tool_id = ?", args: [id] },
    { sql: "DELETE FROM tools WHERE id = ?", args: [id] },
  ], "write");
  console.log(`archived ${id} (restore: bun run scripts/delist-tool.ts ${id} --restore)`);
}

// Regenerate the 410 list the middleware reads (deploy afterwards).
const ids = (await db.execute("SELECT id FROM tools_archive ORDER BY id")).rows.map((r) => String(r.id));
writeFileSync(new URL("../src/lib/delisted-ids.ts", import.meta.url), `// Generated by scripts/delist-tool.ts from tools_archive — do not edit by hand. Deploy after changing.\nexport const DELISTED: readonly string[] = ${JSON.stringify(ids)};\n`);
console.log(`delisted-ids.ts: ${ids.length} id(s) — commit + deploy to update the 410 list`);
